#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="cocaine-tornado-proxy2"
NAME=cocaine-tornado-proxy
PID_PATH=/var/run
USER="cocaine"
START_PORT=8080
TORNADO_COUNT=5 # Count of tornado processes
APPS_COUNT=10 # Count of the same applications in one tornado process 
LOG="/var/log/tornado.log"
LOGLEVEL="info" # debug|info|warning|error|none

if [ $2 ]; then
    TORNADO_COUNT=$2
fi

if [ $3 ]; then
    APPS_COUNT=$3
fi

do_start()
{   
    echo "Start $TORNADO_COUNT tornadoes with $APPS_COUNT endpoints per cocaine application"
    for (( i=1; i<=$TORNADO_COUNT; i++ ))
    do
       PIDFILE=$PID_PATH/tornado-proxy.$i 
       PORT=$(($START_PORT+$i))
       echo -n "Start $i on port $PORT and pid $PIDFILE "
       cocaine-tornado-proxy2 --daemon --port=$PORT --user=$USER --pidfile=$PIDFILE --logging=$LOGLEVEL --log_file_prefix=$LOG --count=$APPS_COUNT start
       if [ $? -ne 0 ]; 
       then
             echo "FAIL"
       else
             echo "OK"
       fi
    done
}

#
# Function that stops the daemon/service
#
do_stop()
{
    PIDS=($(ls -1 $PID_PATH/ | grep tornado))
    if [ ${#PIDS[@]} -gt 0 ]; then
        for pid in "${PIDS[@]}"
        do
            PIDFILE=$PID_PATH/$pid
            cocaine-tornado-proxy2 --daemon --pidfile=$PIDFILE stop
        done
    else
        echo "There are no working processes"
    fi
}


case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  status)
    ;;
  restart|force-reload)
	do_stop
    do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart} [tornadoes_count] [applications count]" >&2
	exit 3
	;;
esac
