#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="cocaine-tornado-proxy"
NAME=cocaine-tornado-proxy
COUNT=5
PID_PATH=/var/run
START_PORT=8080

do_start()
{
    for (( i=1; i<=$COUNT; i++ ))
    do
       PIDFILE=$PID_PATH/tornado-proxy.$i 
       PORT=$(($START_PORT+$i))
       echo "Start $i on port $PORT and pid $PIDFILE"
       cocaine-tornado-proxy --daemon --port=$PORT --pidfile=$PIDFILE start
    done
}

#
# Function that stops the daemon/service
#
do_stop()
{
    for (( i=1; i<=$COUNT; i++ ))
    do
       PIDFILE=$PID_PATH/tornado-proxy.$i 
       PORT=$(($START_PORT+$i))
       cocaine-tornado-proxy --daemon --pidfile=$PIDFILE stop
    done
}


case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  status)
    ;;
  restart|force-reload)
	do_stop
    do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
	exit 3
	;;
esac

:
