#!/bin/bash


LOGDIR="/var/log/cocaine-tornado"
PIDDIR="/var/run/cocaine-tornado"

if [ ! -d "$LOGDIR" ]; then
    mkdir -p $LOGDIR
fi

chown -R cocaine:adm $LOGDIR

if [ ! -d "$PIDDIR" ]; then
    mkdir -p $PIDDIR
fi

chown -R cocaine:adm $PIDDIR

/usr/sbin/update-rc.d cocaine-tornado-proxy defaults

#DEBHELPER#
